kind: pipeline
type: docker
name: default

steps:
  - name: install dependencies
    image: node:18-alpine
    commands:
      - npm install
  - name: test
    image: node:18-alpine
    commands:
      - npm run lint
  - name: build
    image: node:18-alpine
    commands:
      - npm run build
  - name: deploy
    image: node:18-alpine
    commands:
      - npm run start
