kind: pipeline
type: docker
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules

  - name: install depends
    image: node:18
    commands:
      - npm install

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules

  # Other branches
  - name: test
    image: node:18
    when:
      branch:
        exclude:
          - main
    commands:
      - npm run lint

  # Main branches
  - name: docker
    image: plugins/docker
    when:
      branch:
        - main
    settings:
      username:
        from_secret: repo_username
      password:
        from_secret: repo_password
      repo: gitea.example.com/Fascinated/beatsaber-overlay:latest
      #repo: fascinated/beatsaber-overlay
      tags: latest

volumes:
  - name: cache
    host:
      path: /tmp/cache
# deploy:
#   image: alpine:latest
#   stage: deploy
#   tags:
#   script:
#     - chmod og= $ID_RSA
#     - apk update && apk add openssh-client
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /home/overlay && docker compose pull && docker compose up -d && docker image prune -f"
#   environment:
#     name: production
#     url: https://bs-overlay.fascinated.cc
#   only:
#     - main
