kind: pipeline
type: docker
name: default
ports: [3001]

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: fascinated/beatsaber-overlay
      tags: latest
