kind: pipeline
type: docker
name: default
ports: [3001]

steps:
  - name: install dependencies
    image: node:18-alpine
    commands:
      - npm install
  - name: test
    image: node:18-alpine
    commands:
      - npm run lint
  - name: build
    image: node:18-alpine
    commands:
      - npm run build
  - name: docker  
    image: plugins/docker
    settings:
      username: from_secret: dockerhub_username
      password: from_secret: dockerhub_password
      repo: fascinated/beatsaber-overlay
      tags: latest