kind: pipeline
type: docker
name: default
ports: [3001]

steps:
  # Other branches
  - name: install depends
    image: node:18
    when:
      branch:
        exclude:
          - master
    commands:
      - npm install
  - name: test
    image: node:18
    when:
      branch:
        exclude:
          - master
    commands:
      - npm run lint

  # Main branches
  - name: docker
    image: plugins/docker
    when:
      branch:
        - main
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: fascinated/beatsaber-overlay
      tags: latest
