kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: node:18-alpine
    commands:
      - npm run lint
  - name: deploy
    image: node:18-alpine
    commands:
      - npm run start
