kind: pipeline
type: docker
name: default
ports: [3001]

steps:
  # Other branches
  - name: install depends
    image: node:18
      commands:
      - npm install
    when:
      branch:
        exclude:
          - master
  - name: test
    image: node:18
      commands:
      - npm run lint
    when:
      branch:
        exclude:
          - master

  # Main branches
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: fascinated/beatsaber-overlay
      tags: latest
      when:
        branch:
        - main
