stages:
  - First
  - Second

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - workdir/

First:
  stage: First
  image:
    name: docker:latest
    entrypoint: ["/bin/sh", "-c"]
  script:
  - mkdir -p workdir
  - echo "asdf" > workdir/r.txt


Second:
  stage: Second
  image: alpine
  script:
  - cat workdir/r.txt
