publish:
  image: docker:latest
  stage: build
  variables:
    DOCKER_DRIVER: overlay
  # services:
  #   - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - echo "hi"
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - main

deploy:
  image: alpine:latest
  stage: deploy
  tags:
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /home/overlay && docker compose pull && docker compose up -d && docker image prune -f"
  environment:
    name: production
    url: https://bs-overlay.fascinated.cc
  only:
    - main