services:
  beatsaber-overlay:
    image: fascinated/beatsaber-overlay:latest
    restart: always
    env_file:
      - .env.production
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis:
    image: bitnami/redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=<PASSWORD>
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 512mb
