name: Publish

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-20.04
    container: fascinated/docker-images:node-latest
    steps:
      - name: checkout
        uses: https://github.com/actions/checkout@v3

      - name: Login to Repo
        uses: https://github.com/docker/login-action@v2
        with:
          username: ${{ secrets.REPO_USERNAME }}
          password: ${{ secrets.REPO_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: fascinated/beatsaber-overlay:latest
