name: Publish

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    strategy:
      matrix:
        arch: ['ubuntu-latest']
        git-version: ['2.38.4']
    runs-on: ${{ matrix.arch }}
    #container: node:19-alpine
    steps:
      - name: checkout
        uses: https://github.com/actions/checkout@v3

      - name: download docker
        run: |
          wget -q -O /tmp/docker.tgz https://download.docker.com/linux/static/stable/x86_64/docker-20.10.23.tgz \
          && tar --extract --file /tmp/docker.tgz --directory /usr/bin --strip-components 1 --no-same-owner docker/docker \
          && rm -rf /tmp/*  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Repo
        uses: docker/login-action@v2
        with:
          registry: git.fascinated.cc
          username: ${{ secrets.REPO_USERNAME }}
          password: ${{ secrets.REPO_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: git.fascinated.cc/fascinated/beatsaber-overlay:latest
