name: Publish

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: catthehacker/ubuntu:act-latest
    container: node:19-alpine
    steps:
      - name: Login to Repo
        uses: docker/login-action@v2
        with:
          registry: git.fascinated.cc
          username: ${{ secrets.REPO_USERNAME }}
          password: ${{ secrets.REPO_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: git.fascinated.cc/Fascinated/beatsaber-overlay:latest
