name: Publish

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    strategy:
      matrix:
        arch: ['ubuntu-latest']
        git-version: ['2.38.4']
    runs-on: ${{ matrix.arch }}
    container: node:19-alpine
    steps:
      #- uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Repo
        uses: docker/login-action@v2
        with:
          registry: git.fascinated.cc
          username: ${{ secrets.REPO_USERNAME }}
          password: ${{ secrets.REPO_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: git.fascinated.cc/Fascinated/beatsaber-overlay:latest
