name: Publish

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    strategy:
      matrix:
        arch: ["ubuntu-20.04"]
        git-version: ["2.38.4"]
    runs-on: ${{ matrix.arch }}
    container: fascinated/docker-images:node-latest
    steps:
      - name: checkout
        uses: https://github.com/actions/checkout@v3

      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v2

      - name: Login to Repo
        uses: https://github.com/docker/login-action@v2
        with:
          username: ${{ secrets.REPO_USERNAME }}
          password: ${{ secrets.REPO_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: fascinated/beatsaber-overlay:latest
